version: 0.0
os: linux
files:
 - source: /django_project/
   destination: /home/ec2-user/django_project
 - source: /static/
   destination: /home/ec2-user/static
 - source: /web/
   destination: /home/ec2-user/web   
 - source: /users/
   destination: /home/ec2-user/users
 - source: /db.sqlite3
   destination: /home/ec2-user      
 - source: /manage.py
   destination: /home/ec2-user
 - source: /supervisord.conf
   destination: /home/ec2-user
 - source: /requirements.txt
   destination: /home/ec2-user
 - source: /requirements/
   destination: /home/ec2-user/requirements

permissions:
  - object: /home/ec2-user/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/supervisord.conf
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
