# Generated by Django 2.1.3 on 2018-11-06 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 12, 3, 39, 968918, tzinfo=utc)),
        ),
    ]
