# Generated by Django 2.1.3 on 2018-11-06 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181106_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 12, 5, 16, 398768, tzinfo=utc)),
        ),
    ]
