# Generated by Django 2.1.3 on 2018-11-08 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181106_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 11, 46, 6, 964031, tzinfo=utc)),
        ),
    ]
