# Generated by Django 2.1.3 on 2018-11-12 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181112_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 12, 19, 32, 106612, tzinfo=utc)),
        ),
    ]
