# Generated by Django 2.1.3 on 2018-11-12 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20181112_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 13, 53, 48, 688385, tzinfo=utc)),
        ),
    ]
